---
- name: create aggregate
  hosts: localhost
  tasks:
    - name: Create New_Vol
      netapp.ontap.na_ontap_volume:
        state: present
        name: New_Vol
        is_infinite: False
        aggregate_name: n2_data1
        size: 100
        size_unit: mb
        user_id: 1001
        group_id: 2002
        tiering_policy: auto
        export_policy: default
        percent_snapshot_space: 60
        vserver: FAS2750CL_FC
        wait_for_completion: True
        nvfail_enabled: False
        comment: ansible created volume
        hostname: 192.168.100.53
        username: Ansible
        password: Hitachi@123
